### ISSUE TITLE
Styling 

### ISSUE THREAD

**Issue by Ali-Ozturk** [abhijithvijayan/react-minimal-side-navigation#1]
Hello, great component and easy to use. But is there any way to actually style the buttons - the nav-sub-items etc. ? I can't find any way to give them specific classes or anything. Thanks

**Comment by abhijithvijayan** [comment]
I will add classes to all the components.

**Comment by Ali-Ozturk** [comment]
I'm working on a project and need the sidebar soon. Would that be an implementation you consider to make in the near future? Just wondering if I should look into other similar components or wait :) Thanks for the fast answer btw!

**Comment by abhijithvijayan** [comment]
I will do that in an hour or so

**Comment by Ali-Ozturk** [comment]
> I will do that in an hour or so

Wow that would be great. Looking forward to it, thank you!

**Comment by abhijithvijayan** [comment]
@Ali-Ozturk Released in `1.5.1`

Every item has a unique class name to it.

Closing now. Feel free to reopen if the fix doesn't resolve the issue.

There is a plan to migrate to CSS IN JS libaries to handle the tailwindcss classes to reduce classnames on elements, but even then these classes will be kept as such.

**Comment by davekedar** [comment]
Can I add icon to Sub Navigation ?
