### ISSUE TITLE
Submenu Icon

### ISSUE THREAD

**Issue by madhavpandhare** [abhijithvijayan/react-minimal-side-navigation#13]
How can i add the icon for sub menu?

**Comment by abhijithvijayan** [comment]
this is a good issue. I haven't really thought of that before.

Currently, its not supported. I will implement with the same API soon.

**Comment by abhijithvijayan** [comment]
@madhavpandhare This is now released in `v1.9.1`.

Demo: https://codesandbox.io/s/react-minimal-side-navigation-example-y299d?file=/src/components/NavSidebar.jsx

Closing. Re-open if it doesn't solve the issue.

**Comment by madhavpandhare** [comment]
It's a quick response. thanks a lot mate.
