### ISSUE TITLE
Hide UL when empty object

### ISSUE THREAD

**Issue by alexlovo** [abhijithvijayan/react-minimal-side-navigation#15]
Is there a way to hide the <ul> if its an empty object {}? It shows the div and pushes the rest downward making it look awkward when hiding according to a variable

**Comment by abhijithvijayan** [comment]
can you create a sample codesandbox or attach the sample code here with screenshots @alexlovo

**Comment by alexlovo** [comment]
```
<Navigation
              activeItemId={location.pathname}
              onSelect={({ itemId }) => { history.push(itemId); }}
              items={[
              {
                  title: "Home",
                  itemId: "/",
                  elemBefore: () => <FontAwesomeIcon icon={faHome} />
                },
                isAuthorized ? {  //authorized is true or false
                  title: "Profile",
                  itemId: "/profile",
                  elemBefore: () => <FontAwesomeIcon icon={faUser} />,
                 
                } : "",  // or adding an empty object {} instead of ""
            ]} />
```

Above is the sample, but its due to the div within the ul that it makes it look like something is there. Also it adds it because it iterates through each item regardless if its empty string ("") or empty object ({})

**Comment by abhijithvijayan** [comment]
Why are you passing empty string or empty object

You can conditionally spread the item instead

```
},
...(isAuthorized && {
   title: "",
   . 
   .
})
]}
```

**Comment by abhijithvijayan** [comment]
@alexlovo this can be resolved with conditional spreading

> https://codesandbox.io/s/react-minimal-side-navigation-example-forked-ojlec?file=/src/components/NavSidebar.jsx

**Comment by abhijithvijayan** [comment]
closing. feel free to re-open if it doesn't solve your issue

**Comment by alexlovo** [comment]
Yes that did work, I see what you mean now. Thank you for your quick response.
