### ISSUE TITLE
activeItemId does not change when re-render the component

### ISSUE THREAD

**Issue by renanr-dev** [abhijithvijayan/react-minimal-side-navigation#5]
<Navigation
              activeItemId={someState}/>

When the state change, the hover effect does not move to the selected item

**Comment by abhijithvijayan** [comment]
Could you attach a gif for this behaviour?

**Comment by renanr-dev** [comment]
I can show you on a call, google meet or anything

**Comment by abhijithvijayan** [comment]
You just use a screen recorder and reproduce the behaviour and save as gif. Then attach here.

**Comment by renanr-dev** [comment]
Okay, i will try to record, but this image may could help to understand
![image](https://user-images.githubusercontent.com/38485203/102355812-22190080-3f8b-11eb-928a-10dc95cc47a4.png)

**Comment by renanr-dev** [comment]
On the DebugConsole you can see that "lastSort" is pointed to  itemId "distance", but the higlight (in blue) continue on Risk on the right screen, that was the initial value

**Comment by abhijithvijayan** [comment]
This should work flawlessly. I am using it in many projects as of now.

Can you just make a codesandbox with the same code?

**Comment by renanr-dev** [comment]
Well, i will try to figure out what is happening, cause the problem probably is in my code, if i dont get anywhere i'll reach you again with the real problem

**Comment by abhijithvijayan** [comment]
Cool. If it doesnt work. Create a reproducible repo with the same code and I will look into it

**Comment by renanr-dev** [comment]
Hey, its me again, finally got time to try it out again.
I have created a brand new repository with your nav, and not work as I described earlier could you please take a look again? Thanks! 
https://github.com/Renan97/testminimalnav

**Comment by abhijithvijayan** [comment]
Sure

**Comment by abhijithvijayan** [comment]
fixed in #6, released in `v1.6.0`

**Comment by abhijithvijayan** [comment]
@Renan97 Could you test this out and see if it works now?
